### ISSUE TITLE
Testing: tests should configure a clean database before running

### ISSUE THREAD

**Issue by blackfist** [blackfist/windmill#8]
Right now if you do `rspec spec` the tests will fail unless you first run `RACK_ENV=test rake db:migrate` to create the database. The database isn't cleaned after the tests run either so the database will just grow and grow.

**Comment by sroberts** [comment]
I was looking at [this thread on stackoverflow](http://stackoverflow.com/questions/25497134/rspec-clean-database-before-running) (because who doesn't love SO driven development, and it sounds like the [database_cleaner](https://rubygems.org/gems/database_cleaner) might be the way to go. I'm just still trying to figure out exactly how to integrate it having not touched RSpec much. I'll give it a look later on today, but wanted to document this.
